### ISSUE TITLE
Add a check to the enable() function in civicrmzapier.php to check if CiviRules is installed

### ISSUE THREAD

**Issue by ErikHommel** [mercimukwe/cm.mercimukwe.civicrmzapier#2]
Need to add something like this:

```
 try {
    $installedExtensions = civicrm_api3('Extension', 'Get', array());
    foreach ($installedExtensions['values'] as $extension) {
      if ($extension['key'] = 'org.civicoop.contactsegment' && $extension['status'] == 'installed') {
        $foundExtension = TRUE;
      }
    }
  } catch (CiviCRM_API3_Exception $ex) {
    throw new Exception(ts('Could not get any extensions in mainsector.php function _checkContactSegmentInstalled,
      error from API Extension Get: '.$ex->getMessage()));
  }
```

**Comment by mercimukwe** [comment]
what is 'Extension'? i believe that is what caught my attention, otherwise i have added the check for the installed extension in the civicrmzapier.php file

**Comment by ErikHommel** [comment]
@mercimukwe  Extension is a CiviCRM extension? So there is an API which returns the list of extensions on your specific CiviCRM installation. Try on the API explorer!

**Comment by mercimukwe** [comment]
@ErikHommel iI started by performing the query to the API and i saw the results, then i have made the addition and modification and made a commit for that. 

![extension querry](https://cloud.githubusercontent.com/assets/18053120/17287271/8de38e2c-57c6-11e6-903b-4761831af42a.png)
