### ISSUE TITLE
Change Exception message in SurveyRequest

### ISSUE THREAD

**Issue by ErikHommel** [mercimukwe/cm.mercimukwe.civicrmzapier#5]
This exception message will probably confuse more than help:
           ```
 throw new Exception('Could not submit request to Zapier through API ' .**METHOD** .'
            check extension API method ' .$ex->getMessage());

```
The _METHOD_ will return the class and method name, not the name of the API. Reconstruct to something meaningful that will help the person receiving the error to find out what is happening.
```

**Comment by mercimukwe** [comment]
Tried to change that to best suit the user. I don't know if that is the best but i can still change it if need be.
